# FindCasablanca package
#
# Tries to find the Casablanca (C++ REST SDK) library
#

# Include dir
FIND_PATH(CASABLANCA_INCLUDE_DIR
  NAMES
    cpprest/http_client.h
  PATHS
    $ENV{CASABLANCA_DIR}
    ${CASABLANCA_DIR}
  PATH_SUFFIXES
    Release/include
    include
  NO_DEFAULT_PATH
)
#MESSAGE("CASABLANCA_INCLUDE_DIR = ${CASABLANCA_INCLUDE_DIR}")

# Library
IF(MSVC)
  SET(CMAKE_FIND_LIBRARY_PREFIXES "")

  SET(MSVC_SUFFIX)
  IF(MSVC12)
    SET(MSVC_SUFFIX_RELEASE "120_2_6.lib")
    SET(MSVC_SUFFIX_DEBUG "120d_2_6.lib")
  ENDIF()

  #MESSAGE("msvc_suffix = ${MSVC_SUFFIX}")
  IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET(ARCH "x64")
  ELSEIF(CMAKE_SIZEOF_VOID_P EQUAL 4)
    SET(ARCH "Win32")
  ELSE()
    SET(ARCH "Unknown")
  ENDIF()

  SET(CASABLANCA_PATH_SUFFIXES_RELEASE "Binaries/${ARCH}/Release/")
  SET(CASABLANCA_PATH_SUFFIXES_DEBUG "Binaries/${ARCH}/Debug/")
  #MESSAGE("PATH_SUFFIXES_RELEASE = ${CASABLANCA_PATH_SUFFIXES_RELEASE}")
  #MESSAGE("PATH_SUFFIXES_DEBUG = ${CASABLANCA_PATH_SUFFIXES_DEBUG}")

  SET(CMAKE_FIND_LIBRARY_SUFFIXES ".lib" "${MSVC_SUFFIX_RELEASE}")
  FIND_LIBRARY(CASABLANCA_LIBRARY_RELEASE
    NAMES
      cpprest
    PATHS
      ${CASABLANCA_PKGCONF_LIBRARY_DIRS}
      ${CASABLANCA_DIR}
      ${CASABLANCA_DIR}
      $ENV{CASABLANCA_DIR}
    PATH_SUFFIXES
      ${CASABLANCA_PATH_SUFFIXES_RELEASE}
  )

  SET(CMAKE_FIND_LIBRARY_SUFFIXES ".lib" "${MSVC_SUFFIX_DEBUG}")
  FIND_LIBRARY(CASABLANCA_LIBRARY_DEBUG
    NAMES
      cpprest
    PATHS
      ${CASABLANCA_PKGCONF_LIBRARY_DIRS}
      ${CASABLANCA_DIR}
      ${CASABLANCA_DIR}
      $ENV{CASABLANCA_DIR}
    PATH_SUFFIXES
      ${CASABLANCA_PATH_SUFFIXES_DEBUG}
      NO_DEFAULT_PATH
  )

  SET(CASABLANCA_LIBRARY
  			debug ${CASABLANCA_LIBRARY_DEBUG}
  			optimized ${CASABLANCA_LIBRARY_RELEASE})

  MESSAGE("CASABLANCA_LIBRARY debug = ${CASABLANCA_LIBRARY_DEBUG}")
  MESSAGE("CASABLANCA_LIBRARY optimized = ${CASABLANCA_LIBRARY_RELEASE}")

ELSEIF(UNIX)
  SET(CMAKE_FIND_LIBRARY_PREFIXES "lib")
  #MESSAGE("BUILD_SHARED_LIBS = ${BUILD_SHARED_LIBS}")
  IF(BUILD_SHARED_LIBS)
  	SET(CMAKE_FIND_LIBRARY_SUFFIXES ".so")
  ELSE()
  	SET(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
  ENDIF()

  SET(CASABLANCA_LIB_DIR_SUFFIX "")
  IF (CMAKE_BUILD_TYPE MATCHES DEBUG)
  	IF(BUILD_SHARED_LIBS)
  		SET(CASABLANCA_LIB_DIR_SUFFIX "Build/Build.debug/Binaries")
  	ELSE()
  		SET(CASABLANCA_LIB_DIR_SUFFIX "Build/Build.debug.static/Binaries")
  	ENDIF()
  ELSE()
  	IF(BUILD_SHARED_LIBS)
  		SET(CASABLANCA_LIB_DIR_SUFFIX "Build/Build.release/Binaries")
  	ELSE()
  		SET(CASABLANCA_LIB_DIR_SUFFIX "Build/Build.release.static/Binaries")
  	ENDIF()
  ENDIF()

  #MESSAGE("CASABLANCA_LIB_DIR_SUFFIX ${CASABLANCA_LIB_DIR_SUFFIX}")
  #MESSAGE("CASABLANCA_DIR = $ENV{CASABLANCA_DIR}")

  FIND_LIBRARY(CASABLANCA_LIBRARY
    NAMES
      cpprest
    PATHS
      $ENV{CASABLANCA_DIR}
      ${CASABLANCA_DIR}
      /usr/local
      /usr
    PATH_SUFFIXES
      ${CASABLANCA_LIB_DIR_SUFFIX}
    NO_DEFAULT_PATH
  )
ENDIF()
#MESSAGE("CASABLANCA_LIBRARY = ${CASABLANCA_LIBRARY}")

SET(CASABLANCA_PROCESS_LIBS CASABLANCA_LIBRARY)
SET(CASABLANCA_PROCESS_INCLUDES CASABLANCA_INCLUDE_DIR)

MARK_AS_ADVANCED(CASABLANCA_LIBRARY CASABLANCA_INCLUDE_DIR)

#IF(UNIX)
#  LIBFIND_PROCESS(CASABLANCA)
#ENDIF()